modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0"

[[mods]]
modId="fallenflowers_console_logger"
version="2.0.9"
displayName="Console Seeker"
displayURL="https://github.com/Fallenflower-modder/MinecraftConsoleSeeker/tree/Release"
credits="DrownedCloud"
authors="DrownedCloud"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.fallenflowers_console_logger]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration